#!/usr/bin/env bash
#
# Ai Arbuz Provider Api — one-command installer (Ubuntu/Debian).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/juushimatsu/ai-arbuz-provider-api/master/install.sh | bash -s -- your-domain.com
# or:
#   ARBUZ_DOMAIN=your-domain.com bash <(curl -fsSL https://raw.githubusercontent.com/juushimatsu/ai-arbuz-provider-api/master/install.sh)
#
# Idempotent — safe to re-run. Option A: it does NOT touch your existing proxy;
# it prints a ready Caddy block for you to add.
#
set -euo pipefail

# ---- settings -------------------------------------------------------------
REPO_OWNER="juushimatsu"
REPO_NAME="ai-arbuz-provider-api"
BRANCH="master"
REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}.git"
INSTALL_DIR="${HOME}/${REPO_NAME}"
DEFAULT_PORT=8088

DOMAIN="${1:-${ARBUZ_DOMAIN:-}}"

# ---- helpers --------------------------------------------------------------
c_g="\033[1;32m"; c_y="\033[1;33m"; c_r="\033[1;31m"; c_0="\033[0m"
log()  { printf "${c_g}==>${c_0} %s\n" "$*"; }
warn() { printf "${c_y}!! ${c_0} %s\n" "$*"; }
die()  { printf "${c_r}xx ${c_0} %s\n" "$*" >&2; exit 1; }

require_apt() {
  command -v apt-get >/dev/null 2>&1 || die "This installer supports Debian/Ubuntu (apt) only."
}

SUDO=""
need_sudo() {
  if [ "$(id -u)" -ne 0 ]; then
    command -v sudo >/dev/null 2>&1 || die "sudo is required but not installed."
    SUDO="sudo"
  fi
}

free_port() {
  local p="$1"
  while ss -ltnH 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${p}\$"; do
    p=$((p + 1))
  done
  echo "$p"
}

env_get() { [ -f "$1" ] && sed -n "s/^$2=//p" "$1" | head -n1 || true; }

# ---- 1. prerequisites -----------------------------------------------------
require_apt
need_sudo

log "Installing prerequisites (curl, git, openssl, ca-certificates, iproute2)..."
$SUDO apt-get update -y -qq
$SUDO apt-get install -y -qq curl git openssl ca-certificates iproute2 >/dev/null

# ---- 2. Docker ------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine + Compose plugin via get.docker.com..."
  curl -fsSL https://get.docker.com | $SUDO sh
fi
if ! docker compose version >/dev/null 2>&1 && ! $SUDO docker compose version >/dev/null 2>&1; then
  die "Docker Compose plugin not available after install."
fi

if [ "$(id -u)" -ne 0 ] && ! id -nG "$(id -un)" 2>/dev/null | tr ' ' '\n' | grep -qx docker; then
  log "Adding $(id -un) to the 'docker' group..."
  $SUDO usermod -aG docker "$(id -un)" || true
fi

# choose how to run docker in THIS session (group change isn't active yet)
if docker info >/dev/null 2>&1; then
  RUN() { bash -c "$*"; }
elif command -v sg >/dev/null 2>&1 && sg docker -c "docker info" >/dev/null 2>&1; then
  RUN() { sg docker -c "$*"; }
else
  RUN() { $SUDO bash -c "$*"; }
fi

# ---- 3. fetch the repository ---------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Updating existing checkout in $INSTALL_DIR..."
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$BRANCH" -q
  git -C "$INSTALL_DIR" checkout -q "$BRANCH"
  git -C "$INSTALL_DIR" reset --hard -q "origin/$BRANCH"
else
  log "Cloning $REPO_URL into $INSTALL_DIR..."
  git clone --depth 1 -b "$BRANCH" "$REPO_URL" "$INSTALL_DIR" -q
fi
cd "$INSTALL_DIR"

# ---- 4. environment / secrets --------------------------------------------
ENV_FILE="$INSTALL_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
  PORT="$(free_port "$DEFAULT_PORT")"
  MASTER_KEY="$(openssl rand -hex 32)"
  ADMIN_PASS="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-24)"
  PUBLIC_URL="https://${DOMAIN:-localhost}"
  [ -z "$DOMAIN" ] && PUBLIC_URL="http://localhost:${PORT}"

  log "First run: generating secrets and .env (port ${PORT})..."
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%FT%TZ). Keep this file private.
# ARBUZ_MASTER_KEY encrypts upstream API keys at rest — NEVER change or lose it.
ARBUZ_MASTER_KEY=${MASTER_KEY}
ARBUZ_ADMIN_LOGIN=admin
ARBUZ_ADMIN_PASSWORD=${ADMIN_PASS}
ARBUZ_PUBLIC_URL=${PUBLIC_URL}
ARBUZ_HOST_PORT=${PORT}
ARBUZ_LOG_LEVEL=info
ARBUZ_GUARD_MODE=block
ARBUZ_LIMIT_FAIL=closed
ARBUZ_CACHE_ENABLED=enabled
ARBUZ_CACHE_TTL_SECONDS=300
EOF
  chmod 600 "$ENV_FILE"
else
  log "Existing .env found — keeping secrets."
  PORT="$(env_get "$ENV_FILE" ARBUZ_HOST_PORT)"; PORT="${PORT:-$(free_port "$DEFAULT_PORT")}"
  grep -q '^ARBUZ_HOST_PORT=' "$ENV_FILE" || echo "ARBUZ_HOST_PORT=${PORT}" >> "$ENV_FILE"
  if [ -n "$DOMAIN" ]; then
    if grep -q '^ARBUZ_PUBLIC_URL=' "$ENV_FILE"; then
      sed -i "s#^ARBUZ_PUBLIC_URL=.*#ARBUZ_PUBLIC_URL=https://${DOMAIN}#" "$ENV_FILE"
    else
      echo "ARBUZ_PUBLIC_URL=https://${DOMAIN}" >> "$ENV_FILE"
    fi
  fi
fi

# ---- 4b. data dir (must be writable by the in-container uid 10001) ---------
# The image runs as a non-root user (uid 10001). On a bind-mounted ./data the
# host ownership wins, so without this the app gets SQLite CANTOPEN ("out of
# memory (14)") and crash-loops. Create and chown the dir up front.
RUN "mkdir -p '$INSTALL_DIR/data'"
RUN "chown -R 10001:10001 '$INSTALL_DIR/data' || chmod -R 777 '$INSTALL_DIR/data'"

# ---- 5. pull (or build) & start -------------------------------------------
# By default we PULL a prebuilt image from GHCR — no compilation on this host,
# so it's fast and won't hog CPU/RAM. Set ARBUZ_BUILD=1 to build from source.
if [ "${ARBUZ_BUILD:-0}" = "1" ]; then
  log "ARBUZ_BUILD=1 -> building image from source (this may take several minutes)..."
  RUN "cd '$INSTALL_DIR' && docker compose up -d --build"
else
  log "Pulling prebuilt image from GHCR (fast, no host compilation)..."
  if RUN "cd '$INSTALL_DIR' && docker compose pull"; then
    RUN "cd '$INSTALL_DIR' && docker compose up -d --no-build"
  else
    warn "Pull failed (image not published yet?). Falling back to local build..."
    RUN "cd '$INSTALL_DIR' && docker compose up -d --build"
  fi
fi

# ---- 6. health check ------------------------------------------------------
log "Waiting for the service to become healthy on 127.0.0.1:${PORT}..."
OK="no"
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${PORT}/api/health" >/dev/null 2>&1; then OK="yes"; break; fi
  sleep 2
done

ADMIN_LOGIN="$(env_get "$ENV_FILE" ARBUZ_ADMIN_LOGIN)"
ADMIN_PASS="$(env_get "$ENV_FILE" ARBUZ_ADMIN_PASSWORD)"

echo
if [ "$OK" = "yes" ]; then
  log "Service is up."
else
  warn "Service did not answer /api/health in time. Check logs:"
  echo "    cd '$INSTALL_DIR' && docker compose logs -f arbuz"
fi

# ---- 7. summary -----------------------------------------------------------
cat <<EOF

--------------------------------------------------------------------
 Ai Arbuz Provider Api -- installed
--------------------------------------------------------------------
 Directory     : ${INSTALL_DIR}
 Local address : http://127.0.0.1:${PORT}   (localhost only)
 Admin login   : ${ADMIN_LOGIN}
 Admin password: ${ADMIN_PASS}

 Secrets (admin password + ARBUZ_MASTER_KEY) live in:
   ${ENV_FILE}
 Back up that file. Do NOT change ARBUZ_MASTER_KEY after first run --
 it decrypts your stored provider keys.
EOF

if [ -n "$DOMAIN" ]; then
  cat <<EOF

 -- Reverse proxy (add this to YOUR Caddy, then reload) --
   ${DOMAIN} {
       reverse_proxy 127.0.0.1:${PORT}
   }

 Reload Caddy, e.g.:
   caddy reload --config /etc/caddy/Caddyfile
   # or in Docker: docker exec <caddy-container> caddy reload --config /etc/caddy/Caddyfile

 Then open: https://${DOMAIN}
EOF
else
  cat <<EOF

 No domain provided. Route a TLS reverse proxy to 127.0.0.1:${PORT}, e.g. Caddy:
   your-domain.com {
       reverse_proxy 127.0.0.1:${PORT}
   }
EOF
fi

cat <<EOF

 Manage:
   cd '${INSTALL_DIR}'
   docker compose ps
   docker compose logs -f arbuz
   docker compose restart
   docker compose down

 NOTE: if Docker was just installed, log out/in once to use 'docker' without sudo.
--------------------------------------------------------------------
EOF